bullhorn/bullhorn-types

- src/index.ts
updates BillableChargeSummaryTransaction entity name
> feat(typings): updating BillableChargeSummaryTransaction entity name

- src/index.ts
> feat(typings): PayBillSetting entity

- src/index.ts
Adds new field to Certification File Attachment
> BH-65656 new isEncrypted field for CertificationFileAttachment

- src/index.ts
Reverts bullhorn/bullhorn-types#28
> Revert "BH-65656 new isEncrypted field for CertificationFileAttachment"

- src/index.ts
Add rebill related fields to Invoice Statement
> feat(typings): add missing rebill fields

- src/index.ts
add isSystem to timeLaborEvalRuleTypeLookup
> feat(typings): add isSystem to timeLaborEvalRuleTypeLookup

- src/index.ts
Adding candidateTaxInfo typing.
> feat(typings): Add CandidateTaxInfo

- src/index.ts
feat(typings): add federaltaxform, statetaxform, and localtaxform entity types
> feat(typings): add federaltaxform, statetaxform, and localtaxform to entity types

- src/index.ts
adds the isDiscountable field to EarnCode
> feat(typings): add isDiscountable field to EarnCode

- src/index.ts
Adding deliveryMethodLookupID to InvoiceStatement
> feat(typings): Adding deliveryMethodLookupID

- src/index.ts
change shiftSetting logo filed to String and update name
> fix(typings): fix ShiftSetting field

- src/index.ts
Fix type (was uppercase String instead of lowercase string)
> fix(typings): fix type casing

- src/index.ts
Add Mass Action Batch, Mass Action Batch Entity, and Mass Action Type Lookup
> feat(typings): Add Mass Action Batch entities

- src/index.ts
feat(typings): added jobShifts to Note
> feat(typings): Note.jobshifts

- src/index.ts
> feat(typings): Add InvoicePayment

- src/index.ts
feat(typings): Add PersonCustomObjectInstance11 - PersonCustomObjectInstance35
> feat(typings): add types for PersonCustomObjectInstance11-35

- src/index.ts
This reverts commit 79c2c58b8bf960030cca7e2b0b8569d9e39b11f3.
> feat(typings): Revert "add client corp rate card entity types (#144)"

- src/index.ts
Add ClientCorporartionRateAgreementCardVersionMatchingCriteria fields to flat entity in order to enable proper field interactions
> feat(typings): Add ClientCorporationRateAgreementCard properties

- src/index.ts
Add the CustomerRequiredFieldConfiguration and Version entity. As well as other related CustomerRequiredField entities (edit history and options).
> feat(typings): Add CustomerRequiredFieldConfiguration entities

- src/index.ts
Adding the CustomerRequiredFieldConfigurationVersionOption entity.
> feat(typings): Add CustomerRequiredFieldConfigurationVersionOption entity

- src/index.ts
Adding the PlacementCredentialDetail entity.
> feat(typings): Add PlacementCredentialDetail entity

- src/index.ts
Changing type from Date to number
> feat(typings): Fix expiringRequirements on PlacementCredentialDetail

- README.md
Commit with whitespace change to trigger release.
> feat(typings): Adding associatedEntityID to CustomerRequiredFieldOption interface

- src/index.ts
Add TimesheetActivity & TimesheetActivityType entities
> feat(typings): Add TimesheetActivity & TimesheetActivityType

- src/index.ts
Update BillMasterCRF entity to include newly added textValue field.
> feat(typings): Update BillMasterCustomerRequiredField entity to add textValue field

- src/index.ts
Added user, dateMofidiedAt, and transactionOrigin properties to Pay and Bill Transaction
> feat(typings): Updated Pay and Bill Transaction types

- src/index.ts
This adds an entity for Accounting Period
> feat(typings): Add AccountingPeriod types

- src/index.ts
Adding PayableChargeSummaryTransaction entity and fields
> feat(typings): Add PayableChargeSummaryTransaction

- src/index.ts
Adding min/max accounting period to payable charge
> feat: Adding min/max accounting period to payable charge

- src/index.ts
feat(typings): Add CopilotPrompt
> feat(typings): Add CopilotPrompt

- src/index.ts
Reverts bullhorn/bullhorn-types#188
> Revert "feat(typings): Adding DirectDepositAccount types"

- src/index.ts
feat(typings): Add DirectDepositAccount
> feat(typings): Add DirectDepositAccount

- src/index.ts
Reverts bullhorn/bullhorn-types#200
> revert feat(typings): shift rate type

- src/index.ts
Adding shift rate type lookup to entity types
> feat(typings): Adding shift rate type lookup

- .github/workflows/main.yaml
Updates actions/cache to v4 version
> fix(actions): Update to github actions

- src/index.ts
Adding new fields to entity types CopilotPrompt, CopilotEntityType, and CopilotPromptRelatedEntitiy
> feat(typings): add new fields to Copilot entities
